/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "border-glass": "rgba(255, 255, 255, 0.10)",
        "on-error": "#690005",
        "surface-tint": "#b4c5ff",
        "on-secondary-fixed-variant": "#2f2ebe",
        "surface-bright": "#33394c",
        "on-primary": "#002a78",
        "surface-container-lowest": "#070d1f",
        "on-primary-container": "#eeefff",
        "on-tertiary-container": "#ffede6",
        "success-emerald": "#10B981",
        "on-surface": "#dce1fb",
        "on-tertiary": "#581e00",
        "primary": "#2563eb",
        "warning-amber": "#F59E0B",
        "on-primary-fixed": "#00174b",
        "surface-container-high": "#23293c",
        "text-muted": "#94A3B8",
        "secondary-container": "#3131c0",
        "tertiary-fixed": "#ffdbcd",
        "primary-container": "#2563eb",
        "on-secondary": "#1000a9",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary-fixed-variant": "#003ea8",
        "on-error-container": "#ffdad6",
        "surface": "#0c1324",
        "surface-container": "#191f31",
        "secondary-fixed": "#e1e0ff",
        "on-tertiary-fixed-variant": "#7d2d00",
        "text-primary": "#F1F5F9",
        "inverse-primary": "#0053db",
        "on-secondary-fixed": "#07006c",
        "inverse-on-surface": "#2a3043",
        "surface-glass": "rgba(255, 255, 255, 0.05)",
        "tertiary": "#ffb596",
        "outline": "#8d90a0",
        "on-background": "#dce1fb",
        "secondary": "#c0c1ff",
        "outline-variant": "#434655",
        "surface-container-low": "#151b2d",
        "on-surface-variant": "#c3c6d7",
        "danger-rose": "#F43F5E",
        "surface-container-highest": "#2e3447",
        "on-tertiary-fixed": "#360f00",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "secondary-fixed-dim": "#c0c1ff",
        "background": "#0c1324",
        "surface-variant": "#2e3447",
        "inverse-surface": "#dce1fb",
        "primary-fixed": "#dbe1ff",
        "on-secondary-container": "#b0b2ff",
        "surface-dim": "#0c1324",
        "tertiary-fixed-dim": "#ffb596",
        "tertiary-container": "#bc4800",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "stack-lg": "24px",
        "stack-xl": "48px",
        "gutter": "24px",
        "stack-md": "16px",
        "container-max": "1440px",
        "stack-xs": "4px",
        "margin-mobile": "16px",
        "stack-sm": "8px",
      },
      fontFamily: {
        h2: ["Sora"],
        h1: ["Sora"],
        h3: ["Sora"],
        "code-md": ["JetBrains Mono"],
        "label-caps": ["JetBrains Mono"],
        "body-md": ["Sora"],
        "body-sm": ["Sora"],
        "body-lg": ["Sora"],
        "code-sm": ["JetBrains Mono"],
      },
      fontSize: {
        h2: ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        h1: ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "code-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        h3: ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "code-sm": ["12px", { lineHeight: "1.4", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
